name: Quality Check

# Run for all commits not in master.
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Tests

    # Use Ubuntu.
    runs-on: ubuntu-latest

    steps:
      # Check out the repository.
      - name: Checkout
        uses: actions/checkout@v2

      # Set up node.
      - name: Set Up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      # Test the project.
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run React Tests
        run: yarn test --ci --maxWorkers=2

      - name: Build the Electron App
        run: yarn build
